name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run:  |
        set -x
        cd src
        ./configure
        make -j

  build-aarch64:
    name: Linux ARM64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu20.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/spaln"
        install: |
          apt-get update -q -y
          apt-get install -q -y make zlib1g-dev
        run: |
          set -x
          cd /spaln/src
          make -j
